# Generated by Django 5.1.1 on 2024-09-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(default='Default description', max_length=255),
            preserve_default=False,
        ),
    ]
