# Generated by Django 5.1.1 on 2024-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(default='cash', max_length=50),
        ),
    ]
