# Generated by Django 5.1.1 on 2024-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
